version: '3.8'
services:
  reactivestack:
    build: docker/.
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:4.4
    ports:
      - "27017:27017"
  redis:
    container_name: redis
    image: redis:6.0.20-alpine
    ports:
      - "6379:6379"
