#
@baseUrl=http://localhost:8080
@bearerAdmin = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJqYXZhLXNwcmluZy1yZWFjdGl2ZS1kZXYiLCJleHAiOjE2OTExMDA0MTgsImlhdCI6MTY5MDc0MDQxOCwic3ViIjoiYWRtaW4ifQ.DaExTyKu_2Zbam8KRaQ4gjBjann-V4uYbkx2-ofU0aE

###
# Access log - read from database
###
POST {{baseUrl}}/bike
Accept: application/json
Content-Type: application/json
Authorization: {{bearerAdmin}}

{
    "name": "carrera",
    "price": 1659.25
}


###
# Access log - read from database
###
GET {{baseUrl}}/bike/5aca6b1a-ad36-469b-8327-1eb689eebf0d
Accept: application/json
Content-Type: application/json
Authorization: {{bearerAdmin}}