#
@baseUrl=http://localhost:8080
@id = 2

GET {{baseUrl}}/hello/{{id}}
Accept: text/plain
Content-Type: application/json
# user
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzYWJhdWRvIiwiaXNzIjoiamF2YS1zcHJpbmctcmVhY3RpdmUiLCJleHAiOjE2OTAwMzgyMTEsImlhdCI6MTY5MDAzNDYxMX0.fstL6wCyWpiR2jgXfyUyQQIb7z8n1XLheIX3Wy82s6Y
# admin
# Authorization: Basic YWRtaW46YWRtaW4=

###
# public controller - no auth nedeed
###
GET {{baseUrl}}/public/{{id}}
Accept: text/plain
Content-Type: application/json

###
# Token
###
POST {{baseUrl}}/token
Accept: application/json
Content-Type: application/json

{
    "name": "sabaudo",
    "secret": "2345678901"
}