#
@baseUrl=http://localhost:8080
@id = 2

GET {{baseUrl}}/hello/{{id}}
Accept: text/plain
Content-Type: application/json
# user
Authorization: Basic dXNlcjp1c2Vy
# admin
# Authorization: Basic YWRtaW46YWRtaW4=

###
# public controller - no auth nedeed
###
GET {{baseUrl}}/public/{{id}}
Accept: text/plain
Content-Type: application/json